<%@ MasterType VirtualPath="~/Site.Master" %>
<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EditDefib.aspx.cs" Inherits="PICUdrugs.drugAdmin.editDefib" %>
<asp:Content ID="Content1" ContentPlaceHolderId="HeadContent" runat="server">
    <link href="<%# ResolveUrl("~/CSS/WardManagement.css")%>" rel="stylesheet" type="text/css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderId="headings" runat="server">
    <h2>Edit Defibrillators</h2>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderId="MainContent" runat="server">

<asp:ObjectDataSource ID="allDefibs" runat="server" 
    SelectMethod="GetDefibs" TypeName="PICUdrugs.BLL.DefibBL"
    DataObjectTypeName="PICUdrugs.DAL.defibModel">
 </asp:ObjectDataSource>

<asp:ObjectDataSource ID="selectedDefib" runat="server" 
    SelectMethod="GetDefibModelById" TypeName="PICUdrugs.BLL.DefibBL"
    DataObjectTypeName="PICUdrugs.DAL.defibModel" DeleteMethod="DeleteDefib" InsertMethod="InsertDefib" UpdateMethod="UpdateDefib"
    ConflictDetection="CompareAllValues" OldValuesParameterFormatString="orig{0}" OnInserted="General_CRUD"  OnUpdated="General_CRUD" OnDeleted="General_CRUD">
     <SelectParameters>
         <asp:ControlParameter ControlId="DefibDropDownList" Name="defibId" PropertyName="SelectedValue" Type="Int32" />
     </SelectParameters>
 </asp:ObjectDataSource>

 <asp:ObjectDataSource ID="selectedDefibJoules" runat="server" 
    SelectMethod="GetDefibJoulesByModelId" TypeName="PICUdrugs.BLL.DefibJouleBL"
    DataObjectTypeName="PICUdrugs.DAL.defibJoule" DeleteMethod="DeleteDefibJoule" InsertMethod="InsertDefibJoule" UpdateMethod="UpdateDefibJoule"
    ConflictDetection="CompareAllValues" OldValuesParameterFormatString="orig{0}" OnInserted="General_CRUD"  OnUpdated="General_CRUD" OnDeleted="General_CRUD">
     <SelectParameters>
         <asp:ControlParameter ControlId="DefibDropDownList" Name="modelId" PropertyName="SelectedValue" Type="Int32" />
     </SelectParameters>
     <UpdateParameters>
         <asp:Parameter Name="DefibJoule" Type="Object" />
         <asp:Parameter Name="origDefibJoule" Type="Object" />
     </UpdateParameters>
</asp:ObjectDataSource>

<div class="modelDetails">
    <div class="selectedDdl">
        Defib Model:
        <asp:DropDownList ID="DefibDropDownList" runat="server"
            DataSourceID="allDefibs" DataTextField="Name" 
            DataValueField="Id" AutoPostBack="true" >
        </asp:DropDownList>
    </div>
    <div class="crudOps">
        <span class="displayDetails">Details</span>
        <div runat="server" ID="hiddenDetails" enableviewstate="false">
            <asp:DetailsView ID="ModelDetailView" runat="server" DataSourceID="selectedDefib" AutoGenerateDeleteButton="true" GridLines="None" OnPreRender="ModelDetailViewPreRender"
                AutoGenerateEditButton="true" AutoGenerateInsertButton="true" AutoGenerateRows="False" cssClass="dptDetails selectedMenuItem" EnableModelValidation="true" DataKeyNames="Id">
                <Fields>
                    <asp:DynamicField DataField="Name" HeaderText="Name" HeaderStyle-CssClass="detailLabel" />
                </Fields>
            </asp:DetailsView>
        </div>
    </div>
    <asp:ValidationSummary runat="server" ID="ValSummary" CssClass="validationError" />
    <asp:ValidationSummary runat="server" ID="InsertValSummary" CssClass="validationError" ValidationGroup="insert" />
</div>

    <asp:ListView ID="JoulesListView" runat="server" DataKeyNames="Id" DataSourceID="selectedDefibJoules" InsertItemPosition="LastItem" OnDataBound="JoulesDataBound">
        <EditItemTemplate>
            <tr>
                <td>
                    <asp:LinkButton ID="UpdateButton" runat="server" CommandName="Update" Text="Update" />
                    <asp:LinkButton ID="CancelButton" runat="server" CommandName="Cancel" Text="Cancel" CausesValidation="false"/>
                </td>

                <td>
                    <asp:HiddenField ID="DefibModelId" runat="server" Value='<%# Bind("defibId") %>' />
                    <asp:HiddenField ID="JouleId" runat="server" Value='<%# Bind("Id") %>' />
                    <asp:DynamicControl runat="server" DataField="Joules" Mode="Edit" />
                </td>

            </tr>
        </EditItemTemplate>
        <EmptyDataTemplate>
            <table runat="server">
                <tr>
                    <td>No data was returned.</td>
                </tr>
            </table>
        </EmptyDataTemplate>
        <InsertItemTemplate>
            <tr style="">
                <td>
                    <asp:LinkButton ID="InsertButton" runat="server" CommandName="Insert" Text="Insert" ValidationGroup="insert" />
                    <asp:LinkButton ID="CancelButton" runat="server" CommandName="Cancel" Text="Clear" CausesValidation="false" />
                </td>

                <td>
                    <asp:HiddenField ID="DefibModelId" runat="server" Value='<%# Bind("defibId") %>' />
                    <asp:DynamicControl runat="server" DataField="Joules" Mode="Insert" ValidationGroup="insert"/>
                </td>
            </tr>
        </InsertItemTemplate>
        <ItemTemplate>
            <tr>
                <td>
                    <asp:LinkButton ID="DeleteButton" runat="server" CommandName="Delete" Text="Delete" CausesValidation="false"/>
                    <asp:LinkButton ID="EditButton" runat="server" CommandName="Edit" Text="Edit" />
                </td>

                <td>
                    <asp:HiddenField ID="JouleId" runat="server" Value='<%# Bind("Id") %>' />
                    <asp:DynamicControl runat="server" DataField="Joules" Mode="ReadOnly" />
                </td>
            </tr>
        </ItemTemplate>
        <LayoutTemplate>
            <table runat="server">
                <tr runat="server">
                    <td runat="server">
                        <table ID="itemPlaceholderContainer" runat="server" border="0" style="">
                            <tr runat="server" style="">
                                <th runat="server"></th>
                                <th runat="server">Joules</th>
                            </tr>
                            <tr ID="itemPlaceholder" runat="server">
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr runat="server">
                    <td runat="server" style=""></td>
                </tr>
            </table>
        </LayoutTemplate>
        <SelectedItemTemplate>
            <tr style="">
                <td>
                    <asp:Button ID="DeleteButton" runat="server" CommandName="Delete" Text="Delete" />
                    <asp:Button ID="EditButton" runat="server" CommandName="Edit" Text="Edit" />
                </td>
                <td>
                    <asp:DynamicControl runat="server" DataField="Id" Mode="ReadOnly" />
                </td>
                <td>
                    <asp:DynamicControl runat="server" DataField="defibId" Mode="ReadOnly" />
                </td>
                <td>
                    <asp:DynamicControl runat="server" DataField="Joules" Mode="ReadOnly" />
                </td>
                <td>
                    <asp:DynamicControl runat="server" DataField="defibModel" Mode="ReadOnly" />
                </td>
                <td>
                    <asp:DynamicControl runat="server" DataField="defibModelReference" Mode="ReadOnly" />
                </td>
                <td>
                    <asp:DynamicControl runat="server" DataField="EntityState" Mode="ReadOnly" />
                </td>
                <td>
                    <asp:DynamicControl runat="server" DataField="EntityKey" Mode="ReadOnly" />
                </td>
            </tr>
        </SelectedItemTemplate>

    </asp:ListView>

</asp:Content>
<asp:Content ID="MyScripts" ContentPlaceHolderId="masterScripts" runat="server">
    <script src="<%# ResolveUrl("~/Scripts/WardManagement.js")%>" type="text/javascript"></script>
</asp:Content>