//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Code.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolusDose
    {
        public int BolusDoseId { get; set; }
        public int BolusDrugId { get; set; }
        public double MinDosePerKg { get; set; }
        public double MaxDosePerKg { get; set; }
        public double WeightMin { get; set; }
        public double WeightMax { get; set; }
    
        public virtual BolusDrug BolusDrug { get; set; }
    }
}
