//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Code.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolusDrug
    {
        public BolusDrug()
        {
            this.BolusDoses = new HashSet<BolusDose>();
            this.BolusSortOrderings = new HashSet<BolusSortOrdering>();
        }
    
        public int BolusDrugId { get; set; }
        public string DrugName { get; set; }
        public string Route { get; set; }
        public double Conc_ml { get; set; }
        public string Units { get; set; }
        public string AmpuleConcentration { get; set; }
        public double AdultMax { get; set; }
    
        public virtual ICollection<BolusDose> BolusDoses { get; set; }
        public virtual ICollection<BolusSortOrdering> BolusSortOrderings { get; set; }
    }
}
