//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Code.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefibModel
    {
        public DefibModel()
        {
            this.DefibJoules = new HashSet<DefibJoule>();
            this.Wards = new HashSet<Ward>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DefibJoule> DefibJoules { get; set; }
        public virtual ICollection<Ward> Wards { get; set; }
    }
}
