//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Code.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefibJoule
    {
        public int Id { get; set; }
        public int DefibId { get; set; }
        public int Joules { get; set; }
    
        public virtual DefibModel DefibModel { get; set; }
    }
}
