//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Code.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilutionMethod
    {
        public DilutionMethod()
        {
            this.FixedTimeDilutions = new HashSet<FixedTimeDilution>();
            this.VariableTimeDilutions = new HashSet<VariableTimeDilution>();
            this.VariableTimeDilutions1 = new HashSet<VariableTimeDilution>();
        }
    
        public int DilutionMethodId { get; set; }
        public string Description { get; set; }
        public bool IsNeat { get; set; }
        public bool IsVaryConcentration { get; set; }
        public bool IsVaryVolume { get; set; }
        public bool IsPerKg { get; set; }
    
        public virtual ICollection<FixedTimeDilution> FixedTimeDilutions { get; set; }
        public virtual ICollection<VariableTimeDilution> VariableTimeDilutions { get; set; }
        public virtual ICollection<VariableTimeDilution> VariableTimeDilutions1 { get; set; }
    }
}
