//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Code.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugRoute
    {
        public DrugRoute()
        {
            this.InfusionDrugs = new HashSet<InfusionDrug>();
        }
    
        public int RouteId { get; set; }
        public string Description { get; set; }
        public string Abbrev { get; set; }
    
        public virtual ICollection<InfusionDrug> InfusionDrugs { get; set; }
    }
}
