//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Code.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedTimeConcentration
    {
        public int InfusionConcentrationId { get; set; }
        public int InfusionDilutionId { get; set; }
        public double Concentration { get; set; }
        public Nullable<int> Volume { get; set; }
        public int StopMinutes { get; set; }
        public double Rate { get; set; }
    
        public virtual FixedTimeDilution FixedTimeDilution { get; set; }
    }
}
