//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Code.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiPrefix
    {
        public SiPrefix()
        {
            this.FixedTimeDilutions = new HashSet<FixedTimeDilution>();
            this.InfusionDrugs = new HashSet<InfusionDrug>();
            this.VariableTimeDilutions = new HashSet<VariableTimeDilution>();
        }
    
        public int SiPrefixVal { get; set; }
        public string StrVal { get; set; }
    
        public virtual ICollection<FixedTimeDilution> FixedTimeDilutions { get; set; }
        public virtual ICollection<InfusionDrug> InfusionDrugs { get; set; }
        public virtual ICollection<VariableTimeDilution> VariableTimeDilutions { get; set; }
    }
}
