//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("BolusSortOrdering")]
    public class BolusSortOrdering
    {
        public const int maxBolusSubHeaderLength = 512;
        [Key]
        public int BolusSortOrderId { get; set; }
        [ForeignKey("Ward")]
        public int WardId { get; set; }
        [ForeignKey("BolusDrug")]
        public Nullable<int> BolusDrugId { get; set; }
        public int SortOrder { get; set; }
        [StringLength(maxBolusSubHeaderLength)]
        public string SectionHeader { get; set; }
    
        public virtual BolusDrug BolusDrug { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
