//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DoseCat
    {
        [Key]
        public int DoseCatId { get; set; }
        public string Category { get; set; }
        public byte SortOrder { get; set; }
    
        public virtual ICollection<VariableTimeConcentration> VariableTimeConcentrations { get; set; }
    }
}
