//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DrugRoute : IDateModified
    {
        [Key]
        public int RouteId { get; set; }
        public string Description { get; set; }
        public string Abbrev { get; set; }
        public DateTime DateModified { get; set; }

        public virtual ICollection<InfusionDrug> InfusionDrugs { get; set; }
    }
}
