//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.Pages {
    
    
    public partial class PatientSpecificDrugChart {
        
        /// <summary>
        /// PreviousPage property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new PICUdrugs.Pages.EnterPtData PreviousPage {
            get {
                return ((PICUdrugs.Pages.EnterPtData)(base.PreviousPage));
            }
        }
    }
}
