<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="WardManagement.ascx.cs" Inherits="PICUdrugs.websiteAdmin.WardManagement" %>
 <asp:ObjectDataSource ID="allDpts" runat="server" 
    SelectMethod="GetDepartments" TypeName="PICUdrugs.BLL.WardBL"
    DataObjectTypeName="PICUdrugs.DAL.Ward">
 </asp:ObjectDataSource>
<asp:ObjectDataSource ID="allDefibs" runat="server" 
    SelectMethod="GetDefibs" TypeName="PICUdrugs.BLL.DefibBL"
    DataObjectTypeName="PICUdrugs.DAL.defibModel">
 </asp:ObjectDataSource>

 <asp:ObjectDataSource ID="SelectedDptObjDataSrc" runat="server" 
    SelectMethod="GetDepartmentByWardId" TypeName="PICUdrugs.BLL.WardBL"
    DataObjectTypeName="PICUdrugs.DAL.Ward" DeleteMethod="DeleteWard" InsertMethod="InsertWard" UpdateMethod="UpdateWard"
    ConflictDetection="CompareAllValues" OldValuesParameterFormatString="orig{0}" OnInserted="General_CRUD"  OnUpdated="General_CRUD" OnDeleted="General_CRUD">
     <SelectParameters>
         <asp:ControlParameter ControlId="DptDropDownList" Name="dptId" PropertyName="SelectedValue" Type="Int32" />
     </SelectParameters>
</asp:ObjectDataSource>

<div class="modelDetails">
    <div class="selectedDdl">
        Department: 
        <asp:DropDownList ID="DptDropDownList" runat="server"
            DataSourceID="allDpts" DataTextField="abbrev" OnDataBound="DptDropDownList_DataBound" OnPreRender="DptDropDownList_PreRender"
            DataValueField="WardId" AutoPostBack="true" >
        </asp:DropDownList>
    </div>
    <div class="crudOps">
        <span class="displayDetails">Details</span>
        <div runat="server" id="hiddenDetails" enableviewstate="false">
            <asp:DetailsView ID="dptDetailView" runat="server" DataSourceID="SelectedDptObjDataSrc" GridLines="None" OnPreRender="dptDetailViewPreRender" AutoGenerateDeleteButton="true"
                AutoGenerateEditButton="true" AutoGenerateInsertButton="true" AutoGenerateRows="False" cssClass="dptDetails selectedMenuItem" EnableModelValidation="true" DataKeyNames="WardId">
                <Fields>
                    <asp:DynamicField DataField="Fullname" HeaderText="Name" ValidationGroup="WardValSummary" HeaderStyle-CssClass="detailLabel" />
                    <asp:DynamicField DataField="Abbrev" HeaderText="Abbreviation" ValidationGroup="WardValSummary" HeaderStyle-CssClass="detailLabel" />
                    <asp:TemplateField HeaderText="Defibrillator" HeaderStyle-CssClass="detailLabel">
		                <ItemTemplate>
			                <%#Eval("DefibModel.Name")%>
		                </ItemTemplate>
		                <InsertItemTemplate>
			                <asp:DropDownList ID="DefibList" datasourceid="allDefibs"
				                datatextfield="Name" DataValueField="Id"  
				                SelectedValue='<%# Bind("DefibId") %>' runat="server"/>
		                </InsertItemTemplate>
		                <EditItemTemplate>
			                <asp:DropDownList ID="DefibList" datasourceid="allDefibs"
				                datatextfield="Name" DataValueField="Id"  
				                SelectedValue='<%# Bind("DefibId") %>' runat="server"/>
		                </EditItemTemplate>
	                </asp:TemplateField>
                    <asp:TemplateField HeaderText="Bolus Chart Header" HeaderStyle-CssClass="detailLabel">
                    	<ItemTemplate>
			                <%#Eval("BolusChartHeader")%>
		                </ItemTemplate>
		                <InsertItemTemplate>
			                <asp:TextBox ID="BolusChartHeader" TextMode="MultiLine"
				                Text='<%# Bind("BolusChartHeader") %>' runat="server"/>
		                </InsertItemTemplate>
		                <EditItemTemplate>
			                <asp:TextBox ID="BolusChartHeader" TextMode="MultiLine"
				                Text='<%# Bind("BolusChartHeader") %>' runat="server"/>
		                </EditItemTemplate>
                    </asp:TemplateField> 
                    <asp:DynamicField DataField="PaddingInCm" HeaderText="Bolus Drug Padding (cm)" ValidationGroup="WardValSummary" HeaderStyle-CssClass="detailLabel" />
                    <asp:CheckBoxField DataField="IsLive" HeaderText="Is Live" HeaderStyle-CssClass="detailLabel"/>
                </Fields>
            </asp:DetailsView>
        </div>
    </div>
    <asp:ValidationSummary runat="server" ID="WardValSummary" ValidationGroup="WardVal" CssClass="validationError" />
</div>
