//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICUdrugs.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Ward
    {
        [Key]
        public int WardId { get; set; }
        public string Abbrev { get; set; }
        public string Fullname { get; set; }
        [ForeignKey("DefibModel")]
        public int DefibId { get; set; }
        public bool IsLive {get; set;}
        [Range(0,2, ErrorMessage="Padding must be between 0 and 2cm")]
        public double PaddingInCm { get; set; }
        [StringLength(50)]
        public string BolusChartHeader { get; set; }
    
        public virtual ICollection<BolusSortOrdering> BolusSortOrderings { get; set; }
        public virtual DefibModel DefibModel { get; set; }
        public virtual ICollection<InfusionSortOrdering> InfusionSortOrderings { get; set; }
    }
}
